name: Go
on: [push,pull_request]
jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4  # <-- 改成 v4
      with:
        go-version: 'stable'     # <-- 自动使用最新的稳定版 Go
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Build & Test
      run: make ci
